/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __edu_ucsd_ccdb_glvolume_JNIResolutionVolume__
#define __edu_ucsd_ccdb_glvolume_JNIResolutionVolume__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jint JNICALL Java_edu_ucsd_ccdb_glvolume_JNIResolutionVolume_getVolume (JNIEnv *env, jobject, jstring);
JNIEXPORT void JNICALL Java_edu_ucsd_ccdb_glvolume_JNIResolutionVolume_init (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_edu_ucsd_ccdb_glvolume_JNIResolutionVolume_redrawp (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_edu_ucsd_ccdb_glvolume_JNIResolutionVolume_dummy (JNIEnv *env, jobject, jobject);
JNIEXPORT void JNICALL Java_edu_ucsd_ccdb_glvolume_JNIResolutionVolume_paint (JNIEnv *env, jobject, jobject);

#undef edu_ucsd_ccdb_glvolume_JNIResolutionVolume_serialVersionUID
#define edu_ucsd_ccdb_glvolume_JNIResolutionVolume_serialVersionUID 3613482352429075789LL

#ifdef __cplusplus
}
#endif

#endif /* __edu_ucsd_ccdb_glvolume_JNIResolutionVolume__ */
