/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>
#include "JNIResolutionVolume.h"
#include "vvvirtexrendmngr.h"
#include <stdio.h>

JNIEXPORT jint JNICALL Java_edu_ucsd_ccdb_glvolume_JNIResolutionVolume_getVolume (JNIEnv *env, jobject, jstring)
{

}


JNIEXPORT void JNICALL Java_edu_ucsd_ccdb_glvolume_JNIResolutionVolume_init (JNIEnv *env, jobject)
{
	printf("Resolution volume initilized\n");
}



JNIEXPORT void JNICALL Java_edu_ucsd_ccdb_glvolume_JNIResolutionVolume_redrawp (JNIEnv *env, jobject)
{

}
