/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __jtiffLoader__
#define __jtiffLoader__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_jtiffLoader_hello (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_jtiffLoader_getImageW (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_jtiffLoader_getImageH (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_jtiffLoader_getTileW (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_jtiffLoader_getTileH (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_jtiffLoader_init (JNIEnv *env, jobject, jstring, jlong, jlong, jfloat);
JNIEXPORT jint JNICALL Java_jtiffLoader_getCompressionSceme (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_jtiffLoader_getPixelFormat (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_jtiffLoader_getBytesPerPixel (JNIEnv *env, jobject);
JNIEXPORT jintArray JNICALL Java_jtiffLoader_getRGBA (JNIEnv *env, jobject, jdouble, jdouble, jdouble, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif

#endif /* __jtiffLoader__ */
