package edu.ucsd.ccdb.ontomorph2.core.semantic;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;

import edu.stanford.smi.protegex.owl.model.OWLIndividual;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.OWLNamedClass;
import edu.ucsd.ccdb.ontomorph2.core.data.GlobalSemanticRepository;
import edu.ucsd.ccdb.ontomorph2.core.data.LocalSemanticRepository;
import edu.ucsd.ccdb.ontomorph2.core.data.SemanticRepository;
import edu.ucsd.ccdb.ontomorph2.util.Log;
import edu.ucsd.ccdb.ontomorph2.util.OMTOfflineException;

/** 
 * Represents an OWL class.
 * 
 * @author Stephen D. Larson (slarson@ncmir.ucsd.edu)
 *
 */
public class SemanticClass extends SemanticThingImpl {

	public static final String DENTATE_GYRUS_GRANULE_CELL_CLASS = "nif_cell:nifext_153";
	public static final String CA3_PYRAMIDAL_CELL_CLASS = "nif_cell:nifext_158";
	public static final String CA1_PYRAMIDAL_CELL_CLASS = "nif_cell:nifext_157";
	public static final String MITOCHONDRION_CLASS = "sao:sao1860313010";
	public static final String DENDRITE_CLASS = "sao:sao1211023249";
	public static final String APICAL_DENDRITE_CLASS = "sao:sao1211023249";
	public static final String SOMA_CLASS = "sao:sao1044911821";
	public static final String AXON_CLASS = "sao:sao1770195789";
	public static final String OBJECT_CLASS = "snap:Object";
	public static final String INDEPENDENT_CONTINUANT_CLASS = "snap:IndependentContinuant";
	public static final String CELL_CLASS = "sao:sao1813327414";
	public static final String HIPPOCAMPUS_CLASS = "birn_anat:birnlex_721";
	
	public static int counter = 1;
	
	OWLNamedClass OWLClass = null;

	public SemanticClass(OWLNamedClass owlClass, String uri) {
		this(owlClass);
		this.URI = uri;
	}
	
	public SemanticClass(OWLNamedClass owlClass) {
		OWLClass = owlClass;
	}

	/**
	 * Get the OWL label
	 */
	public String getLabel() {
		return SemanticRepository.getAvailableInstance().getClassLabel(OWLClass, URI);
	}
	
	public String toString() {
		return getLabel();
	}
	
	/**
	 * Get direct instances of this class
	 * @return
	 */
	public List<SemanticInstance> getInstances() {
		List<SemanticInstance> l = new ArrayList<SemanticInstance>();
		Collection instances = OWLClass.getInstances(false);
		for (Iterator it = instances.iterator(); it.hasNext();) {
			SemanticInstance si = new SemanticInstance((OWLIndividual)it.next());
			l.add(si);
		}
		return l;
	}

	public List<SemanticInstance> getAllInstances(OWLModel owlModel) {
		List<SemanticInstance> si = new ArrayList<SemanticInstance>();
		Collection c = owlModel.getInstances(OWLClass);
		for (Iterator it = c.iterator(); it.hasNext();) {
			OWLIndividual ind = (OWLIndividual)it.next();
			si.add(new SemanticInstance(ind));
		}
		return si;
	}

	public String getId() {
		return OWLClass.getName();
	}
	
	public String getURI() {
		return this.URI;
	}
	
	public OWLNamedClass getOWLClass() {
		return OWLClass;
	}
	
	/**
	 * Creates an individual of this class in the knowledge base
	 * @return a SemanticInstance that encapsulates the new individual.  its name has been autogenerated
	 */
	public SemanticInstance createInstance()
	{
		try
		{
			assert OWLClass != null;
		
			return new SemanticInstance(OWLClass.createOWLIndividual(this.getLabel() + "_00" + counter++));
		}
		catch(Exception e)
		{
			System.err.println("ERROR: could not create instance");
			return null;
		}
	}
	
	public boolean equals(Object o) {
		if (o != null && o instanceof SemanticClass) {
			SemanticClass i = (SemanticClass)o;
			if (OWLClass.equals(i.getOWLClass()))
				return true;
		}
		return false;
	}
	
	public int hashCode() {
		return OWLClass.hashCode();
	}
}
