package edu.ucsd.ccdb.ontomorph2.view.misc;

/**
 * @$comment Allows users to search for different semantic entities by name, location or other
 *  property, component, property of a component.  Displays the results of the 
 * search in a list.  Allows the user to save these results to an implicit class 
 * which gets an autogenerated name based on the query
 */

public class EntitySearchPanel {
}
